"""Seed the database with initial markets on first run."""
from datetime import datetime, timezone
from sqlalchemy import select
from app.database import AsyncSessionLocal
from app.models.market import Market, MarketCategory, MarketStatus
from app.models.price_history import PriceHistory
from app.core import lmsr

# June 5, 2026 news markets (short-term, high urgency)
JUNE_2026_MARKETS = [
    {
        "id": "dolar-1740-hoy",
        "question": "¿Cierra el dólar arriba de $17.40 pesos HOY?",
        "description": "El dólar abrió hoy en 17.32 pesos y está bajo presión alcista por el dato de empleo de EE.UU. ¿Cierra arriba o abajo de 17.40?",
        "category": MarketCategory.ECONOMIA,
        "resolution_criteria": "Resuelve SÍ si el tipo de cambio FIX publicado por Banco de México hoy 5 de junio cierra en ≥17.40 pesos por dólar.",
        "ends_at": datetime(2026, 6, 5, 23, 59, tzinfo=timezone.utc),
        "b": 50.0,
        "initial_yes_price": 35.0,
        "trending": True,
    },
    {
        "id": "dolar-1750-semana",
        "question": "¿Supera el dólar los $17.50 pesos esta semana?",
        "description": "El peso está en zona de presión tras el NFP americano sorpresivamente sólido. ¿Toca el dólar 17.50 o más antes del cierre del lunes?",
        "category": MarketCategory.ECONOMIA,
        "resolution_criteria": "Resuelve SÍ si el tipo de cambio interbancario Bloomberg o el FIX de Banxico alcanza ≥17.50 en cualquier momento antes del 8 de junio.",
        "ends_at": datetime(2026, 6, 8, 23, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 25.0,
        "trending": True,
    },
    {
        "id": "sp500-semana-verde",
        "question": "¿Termina el S&P 500 la semana en verde?",
        "description": "El S&P 500 cae 0.63% hoy tras el dato de empleo que apunta a tasas más altas de la Fed. ¿Cierra la semana en positivo respecto al cierre del viernes pasado?",
        "category": MarketCategory.MERCADOS_GLOBALES,
        "resolution_criteria": "Resuelve SÍ si el precio de cierre del S&P 500 el viernes 5 de junio es mayor al cierre del viernes anterior (29 de mayo). Fuente: Bloomberg o Yahoo Finance.",
        "ends_at": datetime(2026, 6, 5, 21, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 40.0,
        "trending": False,
    },
    {
        "id": "btc-62k-finde",
        "question": "¿Cierra Bitcoin arriba de $62,000 el domingo?",
        "description": "BTC cotiza en $62,141 hoy. Con el mercado presionado por tasas al alza, ¿cierra el domingo arriba o abajo de $62,000?",
        "category": MarketCategory.CRYPTO,
        "resolution_criteria": "Resuelve SÍ si el precio de cierre de BTC/USD en CoinGecko.com el domingo 7 de junio es ≥62,000.",
        "ends_at": datetime(2026, 6, 7, 23, 59, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 52.0,
        "trending": True,
    },
    {
        "id": "btc-soporte-60k",
        "question": "¿Toca Bitcoin $60,000 o menos antes del lunes?",
        "description": "Bitcoin está poniendo a prueba el soporte de $60,000 hoy mismo. ¿Lo rompe hacia abajo antes del lunes 8 de junio?",
        "category": MarketCategory.CRYPTO,
        "resolution_criteria": "Resuelve SÍ si el precio mínimo registrado en CoinGecko.com entre el 5 y el 7 de junio es ≤60,000 USD.",
        "ends_at": datetime(2026, 6, 7, 23, 59, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 30.0,
        "trending": True,
    },
    {
        "id": "btc-5pct-movimiento",
        "question": "¿Mueve Bitcoin más de 5% (en cualquier dirección) entre hoy y el lunes?",
        "description": "Con el NFP sólido y la reunión de la Fed el 16-17 de junio, hay momentum en ambas direcciones. ¿Se mueve Bitcoin más de 5% desde su precio de hoy ($62,141)?",
        "category": MarketCategory.CRYPTO,
        "resolution_criteria": "Resuelve SÍ si el precio de cierre del lunes 8 de junio en CoinGecko.com es menor a $59,034 o mayor a $65,248 (±5% de $62,141).",
        "ends_at": datetime(2026, 6, 8, 23, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 45.0,
        "trending": False,
    },
    {
        "id": "fed-probabilidad-70",
        "question": "¿Supera el 70% la probabilidad implícita de subida de tasas Fed esta semana?",
        "description": "Hoy el mercado ya descuenta completamente una subida de tasas antes de fin de año. ¿Supera el 70% la probabilidad implícita según CME FedWatch para la reunión de junio?",
        "category": MarketCategory.MERCADOS_GLOBALES,
        "resolution_criteria": "Resuelve SÍ si la CME FedWatch Tool muestra una probabilidad ≥70% de subida de tasas para la reunión del 16-17 de junio, en cualquier momento antes del 8 de junio.",
        "ends_at": datetime(2026, 6, 8, 22, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 55.0,
        "trending": False,
    },
    {
        "id": "nasdaq-cae-2pct-hoy",
        "question": "¿Cierra el Nasdaq con caída mayor al 2% hoy?",
        "description": "El Nasdaq cae 0.98% en apertura tras el dato de empleo. ¿Termina la jornada con una caída total mayor al 2%?",
        "category": MarketCategory.MERCADOS_GLOBALES,
        "resolution_criteria": "Resuelve SÍ si el cierre del Nasdaq Composite el 5 de junio refleja una caída mayor al 2% respecto al cierre del día anterior. Fuente: Yahoo Finance o Bloomberg.",
        "ends_at": datetime(2026, 6, 5, 22, 0, tzinfo=timezone.utc),
        "b": 50.0,
        "initial_yes_price": 25.0,
        "trending": False,
    },
    {
        "id": "mexico-gana-sudafrica",
        "question": "¿Gana México en su debut vs Sudáfrica en el Mundial?",
        "description": "México debuta en el Mundial 2026 el 11 de junio a las 15:00 en el Estadio Azteca contra Sudáfrica. ¿Gana el Tri? Empate o derrota resuelve NO.",
        "category": MarketCategory.MUNDIAL_2026,
        "resolution_criteria": "Resuelve SÍ si México obtiene 3 puntos (victoria) en el partido vs Sudáfrica. Empate o derrota = NO. Fuente: FIFA.com el 11 de junio.",
        "ends_at": datetime(2026, 6, 11, 23, 59, tzinfo=timezone.utc),
        "b": 120.0,
        "initial_yes_price": 70.0,
        "trending": True,
    },
    {
        "id": "mexico-goles-sudafrica",
        "question": "¿Mete México 2 o más goles vs Sudáfrica?",
        "description": "México debuta el 11 de junio en el Azteca. ¿Anota 2 o más goles en el partido?",
        "category": MarketCategory.MUNDIAL_2026,
        "resolution_criteria": "Resuelve SÍ si México marca ≥2 goles en el partido vs Sudáfrica el 11 de junio. Fuente: FIFA.com.",
        "ends_at": datetime(2026, 6, 11, 23, 59, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 65.0,
        "trending": False,
    },
    {
        "id": "eeuu-gana-paraguay",
        "question": "¿Gana Estados Unidos a Paraguay el 13 de junio?",
        "description": "Estados Unidos vs Paraguay en el Levi's Stadium de San Francisco el 13 de junio. Empate o victoria de Paraguay resuelve NO.",
        "category": MarketCategory.MUNDIAL_2026,
        "resolution_criteria": "Resuelve SÍ si EE.UU. gana el partido vs Paraguay el 13 de junio (resultado final, sin penales de fase de grupos). Fuente: FIFA.com.",
        "ends_at": datetime(2026, 6, 14, 4, 0, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 72.0,
        "trending": True,
    },
    {
        "id": "brasil-gana-marruecos",
        "question": "¿Gana Brasil a Marruecos el 13 de junio?",
        "description": "Brasil vs Marruecos en el MetLife Stadium de Nueva York el 13 de junio. Empate o victoria de Marruecos resuelve NO.",
        "category": MarketCategory.MUNDIAL_2026,
        "resolution_criteria": "Resuelve SÍ si Brasil gana el partido vs Marruecos el 13 de junio (resultado final). Fuente: FIFA.com.",
        "ends_at": datetime(2026, 6, 14, 4, 0, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 68.0,
        "trending": False,
    },
    {
        "id": "alcalde-metepec-legal",
        "question": "¿Enfrenta el alcalde de Metepec acción legal formal esta semana?",
        "description": "Sheinbaum dijo hoy que las autoridades analizan el caso del alcalde de Metepec por posibles irregularidades. ¿Hay acción legal formal (denuncia, citatorio, orden de comparecencia) antes del lunes?",
        "category": MarketCategory.POLITICA_MX,
        "resolution_criteria": "Resuelve SÍ si la Fiscalía del Estado de México o autoridad competente emite una acción legal formal (denuncia, citatorio, orden de presentación) contra el alcalde antes del 8 de junio. Fuente: comunicados oficiales o cobertura verificada.",
        "ends_at": datetime(2026, 6, 8, 23, 59, tzinfo=timezone.utc),
        "b": 60.0,
        "initial_yes_price": 25.0,
        "trending": False,
    },
    {
        "id": "roxana-guzman-aparece",
        "question": "¿Aparece con vida la periodista Roxana Guzmán esta semana?",
        "description": "La fiscal del Estado de México declaró hoy que localizar a la periodista desaparecida Roxana Guzmán es prioridad. ¿Hay noticias de su localización antes del lunes?",
        "category": MarketCategory.MEXICO,
        "resolution_criteria": "Resuelve SÍ si la Fiscalía del Estado de México o autoridad competente confirma la localización con vida de Roxana Guzmán antes del 8 de junio. Fuente: comunicado oficial o medios nacionales verificados.",
        "ends_at": datetime(2026, 6, 8, 23, 59, tzinfo=timezone.utc),
        "b": 60.0,
        "initial_yes_price": 20.0,
        "trending": False,
    },
    {
        "id": "peso-fuerte-lunes",
        "question": "¿Cierra el peso más fuerte el lunes que hoy?",
        "description": "El peso cotiza en 17.32 pesos por dólar hoy. ¿Cierra el lunes más fuerte (menos pesos por dólar)?",
        "category": MarketCategory.ECONOMIA,
        "resolution_criteria": "Resuelve SÍ si el tipo de cambio FIX de Banxico para el lunes 8 de junio es menor a 17.32 pesos por dólar (peso más fuerte).",
        "ends_at": datetime(2026, 6, 8, 23, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 45.0,
        "trending": False,
    },
    {
        "id": "wti-95-semana",
        "question": "¿Supera el petróleo WTI los $95 por barril esta semana?",
        "description": "El WTI cayó 3% hoy hasta $93.14. ¿Rebota y supera los $95 antes del cierre del lunes?",
        "category": MarketCategory.MERCADOS_GLOBALES,
        "resolution_criteria": "Resuelve SÍ si el precio spot del WTI en Bloomberg, Investing.com o MarketWatch alcanza ≥95 USD/barril en cualquier momento antes del 8 de junio.",
        "ends_at": datetime(2026, 6, 8, 22, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 25.0,
        "trending": False,
    },
    {
        "id": "cnte-bloqueo-cuernavaca",
        "question": "¿Hay otro bloqueo en la autopista México-Cuernavaca antes del lunes?",
        "description": "Esta mañana la CNTE bloqueó la caseta de Tlalpan en la México-Cuernavaca. Con las protestas activas, ¿se repite otro bloqueo en esa misma autopista antes del lunes?",
        "category": MarketCategory.MEXICO,
        "resolution_criteria": "Resuelve SÍ si CAPUFE (@CAPUFE en X/Twitter) o Guardia Nacional Carreteras reporta un nuevo bloqueo en la autopista México-Cuernavaca entre el 5 y el 7 de junio.",
        "ends_at": datetime(2026, 6, 8, 5, 0, tzinfo=timezone.utc),
        "b": 60.0,
        "initial_yes_price": 35.0,
        "trending": False,
    },
    {
        "id": "lluvia-cdmx-3dias",
        "question": "¿Llueve 3 días consecutivos en CDMX esta semana?",
        "description": "El pronóstico indica lluvia ligera sábado, ligera domingo e intensa el lunes. ¿Se cumplen 3 días consecutivos de lluvia en CDMX?",
        "category": MarketCategory.MEXICO,
        "resolution_criteria": "Resuelve SÍ si CONAGUA (smn.conagua.gob.mx) reporta precipitación en CDMX en los tres días consecutivos: sábado 6, domingo 7 y lunes 8 de junio.",
        "ends_at": datetime(2026, 6, 9, 6, 0, tzinfo=timezone.utc),
        "b": 60.0,
        "initial_yes_price": 55.0,
        "trending": False,
    },
    {
        "id": "mexico-mas-goles-apertura",
        "question": "¿Mete México más goles que cualquier otra selección el fin de semana de apertura (11-13 jun)?",
        "description": "En el fin de semana de apertura juegan México, EE.UU., Brasil y otras selecciones. ¿México acumula el mayor número de goles del 11 al 13 de junio?",
        "category": MarketCategory.MUNDIAL_2026,
        "resolution_criteria": "Resuelve SÍ si México tiene el mayor total de goles anotados entre todas las selecciones que juegan del 11 al 13 de junio. En caso de empate en goles entre dos selecciones, resuelve NO. Fuente: FIFA.com.",
        "ends_at": datetime(2026, 6, 14, 4, 0, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 35.0,
        "trending": False,
    },
    {
        "id": "btc-bajo-65k-viernes",
        "question": "¿Sigue Bitcoin por debajo de $65,000 el viernes 12 de junio?",
        "description": "El NFP sólido de hoy y las expectativas de tasas más altas de la Fed presionan a Bitcoin. ¿Se mantiene BTC bajo $65,000 al cierre del próximo viernes?",
        "category": MarketCategory.CRYPTO,
        "resolution_criteria": "Resuelve SÍ si el precio de cierre de BTC/USD en CoinGecko.com el viernes 12 de junio es menor a $65,000 USD.",
        "ends_at": datetime(2026, 6, 12, 23, 59, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 58.0,
        "trending": True,
    },
]

SEED_MARKETS = [
    {
        "id": "morena-2027",
        "question": "¿Ganará Morena las elecciones intermedias de 2027?",
        "description": "Este mercado resuelve SÍ si el partido Morena obtiene la mayoría absoluta en la Cámara de Diputados en las elecciones intermedias de 2027. Resolución basada en resultados oficiales del INE.",
        "category": MarketCategory.POLITICA_MX,
        "resolution_criteria": "Resuelve SÍ si Morena + aliados obtienen más de 251 diputaciones según resultados definitivos del INE.",
        "ends_at": datetime(2027, 6, 6, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 72.0,
        "trending": True,
    },
    {
        "id": "dolar-22",
        "question": "¿Subirá el dólar a más de $22 MXN antes del 1 de julio de 2026?",
        "description": "Mercado sobre el tipo de cambio USD/MXN. Resuelve SÍ si el tipo de cambio spot alcanza o supera $22.00 pesos por dólar en cualquier día hábil antes del 1 de julio de 2026, según datos de Banxico.",
        "category": MarketCategory.ECONOMIA,
        "resolution_criteria": "Resuelve SÍ si el tipo de cambio FIX de Banxico alcanza ≥ $22.00 en cualquier sesión antes del 1 Jul 2026.",
        "ends_at": datetime(2026, 7, 1, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 34.0,
        "trending": True,
    },
    {
        "id": "mexico-mundial-octavos",
        "question": "¿Llegará México a los octavos de final del Mundial 2026?",
        "description": "El Mundial FIFA 2026 se co-organiza en México, USA y Canadá. Resuelve SÍ si la selección mexicana avanza a la fase de octavos de final (ronda de 16). México está en el Grupo B junto a Argentina, Croacia y Nueva Zelanda.",
        "category": MarketCategory.DEPORTES,
        "resolution_criteria": "Resuelve SÍ si México termina en los primeros 2 lugares de su grupo o pasa como mejor tercero. Basado en resultados oficiales FIFA.",
        "ends_at": datetime(2026, 7, 1, tzinfo=timezone.utc),
        "b": 150.0,
        "initial_yes_price": 52.0,
        "trending": True,
    },
    {
        "id": "banxico-tasa",
        "question": "¿Bajará Banxico la tasa a menos de 8% antes de diciembre 2026?",
        "description": "Resuelve SÍ si la Junta de Gobierno de Banxico vota una tasa objetivo del Fondeo Bancario por debajo de 8.00% en cualquier reunión antes del 18 de diciembre de 2026.",
        "category": MarketCategory.ECONOMIA,
        "resolution_criteria": "Basado en comunicados oficiales de Banxico tras cada reunión de política monetaria.",
        "ends_at": datetime(2026, 12, 18, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 61.0,
        "trending": False,
    },
    {
        "id": "fed-recorte",
        "question": "¿Recortará la Fed las tasas antes de septiembre 2026?",
        "description": "Resuelve SÍ si la Reserva Federal de EE.UU. reduce el rango objetivo de fondos federales en al menos 25 puntos base en cualquier reunión del FOMC antes del 1 de septiembre de 2026.",
        "category": MarketCategory.GLOBAL,
        "resolution_criteria": "Basado en comunicados oficiales del FOMC.",
        "ends_at": datetime(2026, 9, 1, tzinfo=timezone.utc),
        "b": 200.0,
        "initial_yes_price": 55.0,
        "trending": True,
    },
    {
        "id": "bitcoin-150k",
        "question": "¿Superará Bitcoin los $150,000 USD antes de diciembre 2026?",
        "description": "Resuelve SÍ si el precio de Bitcoin supera los $150,000 USD en cualquier exchange mayor (Binance, Coinbase) antes del 1 de diciembre de 2026. El ciclo alcista de Bitcoin continúa en 2026.",
        "category": MarketCategory.TECH,
        "resolution_criteria": "Precio basado en promedio de Binance y Coinbase Pro en cualquier momento antes del 1 de diciembre de 2026.",
        "ends_at": datetime(2026, 11, 30, tzinfo=timezone.utc),
        "b": 200.0,
        "initial_yes_price": 58.0,
        "trending": True,
    },
    {
        "id": "nvidia-1000",
        "question": "¿Superará NVIDIA los $1,000 USD por acción en 2026?",
        "description": "Resuelve SÍ si el precio de cierre de NVDA en NASDAQ supera los $1,000 USD en cualquier sesión durante el año 2026.",
        "category": MarketCategory.TECH,
        "resolution_criteria": "Basado en precio de cierre oficial de NASDAQ.",
        "ends_at": datetime(2026, 12, 31, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 42.0,
        "trending": False,
    },
    {
        "id": "cdmx-alcalde",
        "question": "¿Ganará oposición la jefatura de gobierno de CDMX en 2027?",
        "description": "Resuelve SÍ si un candidato de la oposición (distinto a Morena y aliados) gana la Jefatura de Gobierno de la Ciudad de México en las elecciones de 2027.",
        "category": MarketCategory.POLITICA_MX,
        "resolution_criteria": "Basado en resultados definitivos del INE/IECM.",
        "ends_at": datetime(2027, 6, 6, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 28.0,
        "trending": False,
    },
    {
        "id": "tigres-champions",
        "question": "¿Llegará un equipo mexicano a la final de la CONCACAF Champions Cup 2026?",
        "description": "Resuelve SÍ si al menos un club mexicano (Liga MX) llega a la final de la CONCACAF Champions Cup 2026.",
        "category": MarketCategory.DEPORTES,
        "resolution_criteria": "Basado en resultados oficiales de CONCACAF.",
        "ends_at": datetime(2026, 6, 30, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 79.0,
        "trending": False,
    },
    {
        "id": "xochitl-2030",
        "question": "¿Será Xóchitl Gálvez candidata presidencial en 2030?",
        "description": "Resuelve SÍ si Xóchitl Gálvez es registrada formalmente como candidata presidencial por cualquier partido o coalición para las elecciones de 2030.",
        "category": MarketCategory.POLITICA_MX,
        "resolution_criteria": "Resolución basada en registro oficial ante el INE.",
        "ends_at": datetime(2030, 1, 15, tzinfo=timezone.utc),
        "b": 80.0,
        "initial_yes_price": 45.0,
        "trending": False,
    },
    {
        "id": "mundial-2026-campeon-europa",
        "question": "¿Ganará un equipo europeo el Mundial FIFA 2026?",
        "description": "El Mundial FIFA 2026 se juega en Norteamérica (México, USA y Canadá). Resuelve SÍ si el campeón final es una selección de UEFA: España, Francia, Alemania, Inglaterra, Portugal, etc. Europa ha dominado los últimos mundiales.",
        "category": MarketCategory.DEPORTES,
        "resolution_criteria": "Resuelve SÍ si el campeón del Mundial FIFA 2026 es una selección afiliada a UEFA. Basado en resultados oficiales FIFA.",
        "ends_at": datetime(2026, 7, 20, tzinfo=timezone.utc),
        "b": 150.0,
        "initial_yes_price": 61.0,
        "trending": True,
    },
    {
        "id": "mexico-inflacion-2026",
        "question": "¿Cerrará la inflación en México por debajo de 4% en diciembre 2026?",
        "description": "Resuelve SÍ si la tasa de inflación anual de México (INPC) reportada por el INEGI para diciembre de 2026 es menor a 4.0%. Banxico ha estado bajando tasas para estimular la economía en 2026.",
        "category": MarketCategory.ECONOMIA,
        "resolution_criteria": "Basado en el reporte oficial del INEGI sobre el INPC de diciembre 2026, publicado en enero 2027.",
        "ends_at": datetime(2027, 1, 15, tzinfo=timezone.utc),
        "b": 100.0,
        "initial_yes_price": 44.0,
        "trending": False,
    },
]


async def seed_markets() -> None:
    async with AsyncSessionLocal() as db:
        for data in JUNE_2026_MARKETS + SEED_MARKETS:
            exists = await db.execute(select(Market).where(Market.id == data["id"]))
            if exists.scalar_one_or_none():
                continue

            initial_price = data["initial_yes_price"] / 100.0
            q_yes, q_no = lmsr.init_q_for_price(initial_price, data["b"])

            market = Market(
                id=data["id"],
                question=data["question"],
                description=data["description"],
                category=data["category"],
                resolution_criteria=data["resolution_criteria"],
                ends_at=data["ends_at"],
                b=data["b"],
                q_yes=q_yes,
                q_no=q_no,
                yes_price=lmsr.yes_price_pct(q_yes, q_no, data["b"]),
                status=MarketStatus.OPEN,
                trending=data.get("trending", False),
            )
            db.add(market)
            db.add(PriceHistory(
                market_id=market.id,
                yes_price=market.yes_price,
                volume_snapshot=0.0,
            ))
        await db.commit()
